apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermetrics.fullname" . }}-job-config
  labels:
    {{- include "hermetrics.labels" . | nindent 4 }}
type: Opaque
stringData:
  job-config.json: |
{{ .Values.jobConfig | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermetrics.fullname" . }}-api-config
  labels:
    {{- include "hermetrics.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-config.json: |
{{ .Values.apiConfig | indent 4 }}
